import { IconLogo } from "@/components";
import ContainerOverview from "@/components/overview/containerOverview/ContainerOverview";
import HeaderOverview from "@/components/overview/headerOverview/HeaderOverview";
import HeaderTittle from "@/components/overview/headerTittle/HeaderTittle";
import RecentPatients from "@/components/overview/recentPatients/RecentPatients";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Doct | dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "../../public/logo.svg",
  },
};
export default function Home() {
  return (
    <div className="flex flex-col gap-[30px]">
      <HeaderTittle />
      <HeaderOverview />
      <ContainerOverview />
      <RecentPatients />
    </div>
  );
}
