import { TCardAppointment } from "@/types/general.overview";
export const cardAppointment: TCardAppointment[] = [
  {
    key: 1,
    img: "/icons/overview/img-avatar1.png",
    title: "Savannah Nguyen",
    time: "45 Male, 12 April 9:30",
    textBtn: "Declined",
    bgColor: "red_button",
    textColorBtn: "red_FF5263",
  },
  {
    key: 2,
    img: "/icons/overview/img-avatar2.png",
    title: "Jacob Jones",
    time: "45 Male, 12 April 9:30",
    textBtn: "Confirmed",
    bgColor: "purple_01",
    textColorBtn: "purple_796EFF",
  },
  {
    key: 3,
    img: "/icons/overview/img-avatar3.png",
    title: "Cody Fisher",
    time: "45 Male, 12 April 9:30",
    textBtn: "Declined",
    bgColor: "red_button",
    textColorBtn: "red_FF5263",
  },
  {
    key: 4,
    img: "/icons/overview/img-avatar4.png",
    title: "Ronald Richards",
    time: "45 Male, 12 April 9:30",
    textBtn: "Confirmed",
    bgColor: "purple_01",
    textColorBtn: "purple_796EFF",
  },
  {
    key: 5,
    img: "/icons/overview/img-avatar5.png",
    title: "Darlene Robertson",
    time: "45 Male, 12 April 9:30",
    textBtn: "Declined",
    bgColor: "red_button",
    textColorBtn: "red_FF5263",
  },
  {
    key: 6,
    img: "/icons/overview/img-avatar6.png",
    title: "Floyd Miles",
    time: "45 Male, 12 April 9:30",
    textBtn: "Declined",
    bgColor: "red_button",
    textColorBtn: "red_FF5263",
  },
  {
    key: 7,
    img: "/icons/overview/img-avatar7.png",
    title: "Marvin McKinney",
    time: "45 Male, 12 April 9:30",
    textBtn: "Confirmed",
    bgColor: "purple_01",
    textColorBtn: "purple_796EFF",
  },
];
